# Generated by Django 4.2.4 on 2023-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tran", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transname", models.CharField(max_length=50)),
                ("seller", models.CharField(max_length=50, verbose_name="판매자")),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("price", models.IntegerField()),
                ("contents", models.TextField()),
            ],
            options={
                "verbose_name": "판매글",
                "db_table": "post",
            },
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
