# Generated by Django 4.2.4 on 2023-08-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tran", "0002_tran_delete_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tran",
            options={"verbose_name": "product"},
        ),
        migrations.RenameField(
            model_name="tran",
            old_name="transname",
            new_name="productname",
        ),
    ]
