# Generated by Django 4.2.4 on 2023-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tran", "0003_alter_tran_options_rename_transname_tran_productname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tran",
            name="price",
            field=models.CharField(max_length=10),
        ),
    ]
