# Generated by Django 4.2.4 on 2023-08-13 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tran", "0005_alter_tran_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tran",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="판매자",
            ),
        ),
    ]
