# Generated by Django 4.2.4 on 2023-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tran", "0006_alter_tran_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tran",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
