# Generated by Django 4.2.4 on 2023-08-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tran", "0007_alter_tran_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="날짜 및 시간"),
                ),
                ("chat", models.CharField(max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tran.tran"
                    ),
                ),
            ],
        ),
    ]
