# Generated by Django 4.2.4 on 2023-08-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tran", "0008_chat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
