# Generated by Django 4.2.4 on 2023-08-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tran", "0009_delete_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tran",
            name="type",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="tran",
            name="productname",
            field=models.CharField(
                choices=[
                    ("non-specified", "기타 작물"),
                    ("root", "뿌리"),
                    ("grain", "곡물"),
                    ("mushroom", "버섯"),
                    ("vegetable", "채소"),
                    ("herbs", "나물"),
                    ("nuts", "견과류"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
