# Generated by Django 4.2.4 on 2023-08-16 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tran", "0017_alter_tran_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tran",
            name="like_count",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="tran",
            name="type",
            field=models.CharField(
                choices=[
                    ("fruits", "과일"),
                    ("vegetable", "채소"),
                    ("non-specified", "기타 작물"),
                    ("root", "뿌리"),
                    ("herbs", "나물"),
                    ("grain", "곡물"),
                    ("nuts", "견과류"),
                    ("mushroom", "버섯"),
                ],
                max_length=400,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like_product",
                    models.ManyToManyField(
                        blank=True, related_name="like_users", to="tran.tran"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
