# Generated by Django 4.2.4 on 2023-08-16 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tran", "0018_tran_like_count_alter_tran_type_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tran",
            name="type",
            field=models.CharField(
                choices=[
                    ("herbs", "나물"),
                    ("fruits", "과일"),
                    ("mushroom", "버섯"),
                    ("non-specified", "기타 작물"),
                    ("root", "뿌리"),
                    ("vegetable", "채소"),
                    ("nuts", "견과류"),
                    ("grain", "곡물"),
                ],
                max_length=400,
                null=True,
            ),
        ),
    ]
