# Generated by Django 4.2.4 on 2023-08-16 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tran", "0022_alter_cart_user_alter_tran_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tran",
            name="like_count",
        ),
        migrations.AddField(
            model_name="tran",
            name="like_user",
            field=models.ManyToManyField(
                blank=True, related_name="like_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tran",
            name="type",
            field=models.CharField(
                choices=[
                    ("root", "뿌리"),
                    ("herbs", "나물"),
                    ("nuts", "견과류"),
                    ("mushroom", "버섯"),
                    ("fruits", "과일"),
                    ("vegetable", "채소"),
                    ("grain", "곡물"),
                    ("non-specified", "기타 작물"),
                ],
                max_length=400,
                null=True,
            ),
        ),
    ]
