# Generated by Django 4.2.4 on 2023-08-16 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tran", "0024_alter_tran_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tran",
            name="like_user",
            field=models.ManyToManyField(
                blank=True, related_name="like_user", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tran",
            name="type",
            field=models.CharField(
                choices=[
                    ("herbs", "나물"),
                    ("mushroom", "버섯"),
                    ("grain", "곡물"),
                    ("nuts", "견과류"),
                    ("root", "뿌리"),
                    ("non-specified", "기타 작물"),
                    ("fruits", "과일"),
                    ("vegetable", "채소"),
                ],
                max_length=400,
                null=True,
            ),
        ),
    ]
