# Generated by Django 4.2.4 on 2023-08-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0050_alter_tran_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='type',
            field=models.CharField(choices=[('nuts', '견과류'), ('grain', '곡물'), ('fruits', '과일'), ('herbs', '나물'), ('mushroom', '버섯'), ('root', '뿌리'), ('vegetable', '채소'), ('non-specified', '기타 작물')], max_length=400, null=True),
        ),
    ]
