# Generated by Django 4.2.4 on 2023-09-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tran', '0051_alter_tran_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tran',
            name='type',
            field=models.CharField(choices=[('herbs', '나물'), ('non-specified', '기타 작물'), ('fruits', '과일'), ('vegetable', '채소'), ('root', '뿌리'), ('mushroom', '버섯'), ('nuts', '견과류'), ('grain', '곡물')], max_length=400, null=True),
        ),
    ]
