# Generated by Django 4.2.4 on 2023-08-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Volun",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("metropolitan", "광역시"),
                            ("gangwon", "강원도"),
                            ("jeolla", "전라도"),
                            ("jeju", "제주도"),
                            ("gyeongsong", "경상도"),
                            ("grain", "경기도"),
                            ("seoul", "서울"),
                            ("chungcheong", "충청도"),
                        ],
                        max_length=400,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "start_period",
                    models.DateField(max_length=64, verbose_name="start period"),
                ),
                (
                    "end_period",
                    models.DateField(max_length=64, verbose_name="end period"),
                ),
                ("hours", models.IntegerField(max_length=10)),
                ("contents", models.TextField()),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판매자",
                    ),
                ),
            ],
            options={
                "verbose_name": "volunteer",
                "db_table": "volunteer",
            },
        ),
    ]
