# Generated by Django 4.2.4 on 2023-08-17 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteer", "0003_alter_volun_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volun",
            name="region",
            field=models.CharField(
                choices=[
                    ("metropolitan", "광역시"),
                    ("gangwon", "강원도"),
                    ("jeolla", "전라도"),
                    ("jeju", "제주도"),
                    ("chungcheong", "충청도"),
                    ("seoul", "서울"),
                    ("grain", "경기도"),
                    ("gyeongsong", "경상도"),
                ],
                max_length=400,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="volun",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="wrtier",
            ),
        ),
    ]
