# Generated by Django 4.2.4 on 2023-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0012_alter_volun_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volun",
            name="region",
            field=models.CharField(
                choices=[
                    ("gyeonggi", "경기도"),
                    ("gyeongsong", "경상도"),
                    ("chungcheong", "충청도"),
                    ("gangwon", "강원도"),
                    ("metropolitan", "광역시"),
                    ("jeju", "제주도"),
                    ("seoul", "서울"),
                    ("jeolla", "전라도"),
                ],
                max_length=400,
                null=True,
            ),
        ),
    ]
