# Generated by Django 4.2.4 on 2023-09-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0016_alter_volun_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volun',
            name='region',
            field=models.CharField(choices=[('gangwon', '강원도'), ('jeju', '제주도'), ('seoul', '서울'), ('chungcheong', '충청도'), ('metropolitan', '광역시'), ('gyeonggi', '경기도'), ('jeolla', '전라도'), ('gyeongsong', '경상도')], max_length=400, null=True),
        ),
    ]
